arrowParens: avoid
singleQuote: true
bracketSpacing: true
endOfLine: lf
semi: false
tabWidth: 2
trailingComma: none
printWidth: 100
overrides:
  - files: '*.js'
    options:
      parser: flow
      printWidth: 80
